### ISSUE TITLE
raspberry pi lite os issue

### ISSUE THREAD

**Issue by hyber-code** [mnk400/holeInfo#1]
after installing the script i get the following error or display

![image](https://user-images.githubusercontent.com/18413990/95815759-ccc83500-0d36-11eb-8ca1-a604079b92a9.png)

**Comment by mnk400** [comment]
Hey! This script is supposed to be used on other devices on the same network, not on the pihole itself. 

But if in case you'd like to use it on pihole uninstall your current version and in file holeinfo.py replace the 11th line with "self.url = "http://localhost/admin"" and install it again.
